name: Sync Readme to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - readme.md
      - .github/workflows/sync-dockerhub-readme.yml

permissions:
  contents: read

jobs:
  sync:
    name: Sync
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Sync Readme to Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          readme-filepath: ./readme.md
